site_name: FFox's Notes
site_url: https://frightenedfoxcn.github.io/notes/

theme: 
  name: 'material'
  language: 'zh'
  icon: 
    logo: material/notebook-outline
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - scheme: slate

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://tikzjax.com/v1/fonts.css
  - css/stylesheet.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js
  - https://tikzjax.pages.dev/tikzjax.js
  - js/katex.js

plugins:
  - changelog
  - search

nav:
  - Home:
    - index.md
    - 更新记录: changelog.md
    - 友链: links.md
    - 待办事项: todo.md
  - Technology:
    - tech/index.md
    - Vulkan Tutorial with Rust:
      - tech/rust-vulkan/index.md
      - 01 计算流水线 Compute Pipeline: tech/rust-vulkan/01ComputePipeline.md
  - Mathematics:
    - math/index.md
    - Theory of Computation Overview:
      - math/toc-notes/index.md
      - 01A 有限自动机和正则语言 Finite Automata & Regular Languages: math/toc-notes/01A.md
  - Exercises:
    - exercises/index.md
    # - 李文威《代数学方法》卷一：基本架构: 
    #   - exercises/wwli-aljabr-1/index.md
    #   - 第四章：群论: exercises/wwli-aljabr-1/ch4.md
  - Quick Notes:
    - qnotes/index.md
    - Theorem Proving in Lean 4: qnotes/theorem_proving_in_lean_4.md
